name: Bot Diario

on:
  schedule:
    - cron: '0 9 * * *'  # Ejecutar todos los días a las 9:00 UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python bot.py
